import Head from "next/head";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { theme } from "../../utils/context/theme";
import { LocalStorageLoadedProvider } from "../../utils/context/localStorageLoaded";
import { AuthProvider } from "../../utils/context/auth";
import { MainContainer } from "./MainContainer";

export const siteTitle = "Colis & Co";

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon_colis&co_light.png" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <LocalStorageLoadedProvider>
          <AuthProvider>
            <MainContainer>{children}</MainContainer>
          </AuthProvider>
        </LocalStorageLoadedProvider>
      </ThemeProvider>
    </>
  );
};
