import Head from "next/head";
import { ResponsiveAppBar as Navbar } from "../Navbar";
import { Footer } from "../Footer";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { theme } from "../../utils/context/theme";

export const siteTitle = "Colis & Co";

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon_colis&co_light.png" />
      </Head>
      <main>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </main>
    </>
  );
};
