import Head from "next/head";
import { App } from "@/components/App";

export default function Home() {
  return (
    <>
      <Head>
        <title>Colis & Co</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon_colis&co_light.png" />
      </Head>
      <main>
        <App />
      </main>
    </>
  );
}
